name: jokes_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  # Check Class Equality
  equatable: ^2.0.7
  # Functional Programming
  dartz: ^0.10.1
  # Remote Api 
  http: ^1.3.0
  # State Management
  flutter_bloc: ^9.1.0
  # Dependency Injection
  get_it: ^8.0.3
  # Local Storage
  shared_preferences: ^2.5.3
  internet_connection_checker: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
